{
 "title": "DASHBOARD SERVER 2003",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\n                                                                                  SERVIDOR WINDOWS 2003"
   }
  },
  {
   "title": "Memoria (RAM + Virtual)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Memoria Utilizada",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nagios_metrics",
     "query": "SELECT last(\"value\") FROM \"nagios_metrics\" WHERE (\"host\" = 'Windows_2003' AND \"metric\" = 'usage') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "Windows_2003" },
      { "condition": "AND", "key": "metric::tag", "operator": "=", "value": "select tag value" }
     ]
    },
    {
     "alias": "Memoria Libre",
     "query": "SELECT 8200 - last(\"value\") FROM \"nagios_metrics\" WHERE (\"host\" = 'Windows_2003' AND \"metric\" = 'usage') AND $timeFilter GROUP BY time($__interval) fill(null) "
    }
   ]
  },
  {
   "title": "Historial CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Uso de CPU",
     "query": "SELECT last(\"value\") FROM \"nagios_metrics\" WHERE (\"host\"::tag = 'Windows_2003' AND \"metric\"::tag = 'Load') AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Almacenamiento Disco C:",
   "type": "gauge",
   "description": "Rojo al quedar menos del 10%",
   "gridPos": { "h": 10, "w": 6, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Espacio Lleno",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nagios_metrics",
     "query": "SELECT last(\"value\") FROM \"nagios_metrics\" WHERE (\"host\" = 'Windows_2003' AND \"metric\" = 'Space')\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric::tag", "operator": "=", "value": "select tag value" }
     ]
    },
    {
     "alias": "Espacio Vacio",
     "query": "SELECT 231 - last(\"value\") FROM \"nagios_metrics\" WHERE (\"host\" = 'Windows_2003' AND \"metric\" = 'Space')"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nagios_metrics",
     "query": "SELECT last(\"value\") FROM \"nagios_metrics\" WHERE (\"host\"::tag = 'Windows_2003' AND \"metric\"::tag = 'Load') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "Windows_2003" },
      { "condition": "AND", "key": "metric::tag", "operator": "=", "value": "Load" }
     ]
    }
   ]
  }
 ]
}